sudo: required
language: node_js
node_js:
  - "14.15.0"
services:
  - docker

before_install:
  - docker build -t 3064604/docker-react -f Dockerfile.dev .

script:
  - docker run 3064604/docker-react npm run test -- --coverage